# Generated by Django 5.2.7 on 2025-10-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_post_id_alter_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guestbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('author', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=50)),
                ('choice', models.CharField(choices=[('하늘', '#d1e8f2'), ('주황', '#fdcc84'), ('노랑', '#feebda'), ('핑크', '#fee6e6'), ('초록', '#e7f1f2')], max_length=6)),
            ],
        ),
    ]
