# Generated by Django 5.2.7 on 2025-10-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_guestbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.CharField(default='sideproject', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='choice',
            field=models.CharField(choices=[('#d1e8f2', '하늘'), ('#fdcc84', '주황'), ('#feebda', '노랑'), ('#fee6e6', '핑크'), ('#e7f1f2', '초록')], default='#d1e8f2', max_length=7),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('sideproject', '사이드 프로젝트'), ('workproject', '회사 프로젝트')], default='sideproject', max_length=50),
        ),
    ]
