# Generated by Django 5.2.7 on 2025-10-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_skills_alter_guestbook_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='title',
            field=models.CharField(default='데이터베이스가 멋저요', max_length=30),
            preserve_default=False,
        ),
    ]
