# Generated by Django 5.2.7 on 2025-10-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_guestbook_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestbook',
            old_name='choice',
            new_name='color',
        ),
    ]
