# Generated by Django 5.2.7 on 2026-03-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
