import {
    CheckSquare,
    ChevronsDownUp,
    CircleDot,
    FileCode,
    GripVertical,
    MousePointerClick,
    PanelTop,
    Search,
    SquareDashed,
} from 'lucide-react';

export const COMPONENTS = [
    {
        title: '아코디언',
        href: '/pages/ui/accordion',
        description: '대화형 콘텐츠에 특화되어 있습니다.',
        type: 'Atom',
        icon: <ChevronsDownUp size={40} color="#ffffff" />,
    },
    {
        title: '체크박스',
        href: '/pages/ui/checkbox',
        description: '동의 등에 사용됩니다.',
        type: 'Atom',
        icon: <CheckSquare size={40} color="#ffffff" />,
    },
    {
        title: '드래그앤드롭',
        href: '/pages/ui/dragdrop',
        description: '요소 리스트들의 순서를 조정합니다.',
        type: 'Atom',
        icon: <GripVertical size={40} color="#ffffff" />,
    },
    {
        title: '에디터',
        href: '/pages/ui/editor',
        description: 'html 코드를 만듭니다.',
        type: 'Molecule',
        icon: <FileCode size={40} color="#ffffff" />,
    },
    {
        title: '아이콘버튼',
        href: '/pages/ui/iconbutton',
        description: '아이콘과 함께하는 버튼입니다.',
        type: 'Molecule',
        icon: <MousePointerClick size={40} color="#ffffff" />,
    },
    {
        title: '모달',
        href: '/pages/ui/modal',
        description: '모달입니다.',
        type: 'Organism',
        icon: <SquareDashed size={40} color="#ffffff" />,
    },
    {
        title: '라디오',
        href: '/pages/ui/radio',
        description: '라디오입니다.',
        type: 'Organism',
        icon: <CircleDot size={40} color="#ffffff" />,
    },
    {
        title: '검색',
        href: '/pages/ui/search',
        description: '검색을 구현합니다.',
        type: 'Organism',
        icon: <Search size={40} color="#ffffff" />,
    },
    {
        title: '탭',
        href: '/pages/ui/tab',
        description: '탭을 구현합니다.',
        type: 'Organism',
        icon: <PanelTop size={40} color="#ffffff" />,
    },
    {
        title: '파일업로드',
        href: '/pages/ui/fileupload',
        description: '파일업로드를 구현합니다.',
        type: 'Organism',
        icon: <PanelTop size={40} color="#ffffff" />,
    },
];
