'use client';

import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import localFont from 'next/font/local';
import { usePathname } from 'next/navigation';
import BreadCrumbs from '../app/layout/breadcrumbs/Breadcrumb.tsx';
import { AppSidebar } from '../components/ui/app-sidebar';

import './globals.css';

const pretendard = localFont({
    src: './assets/fonts/PretendardVariable.woff2',
    display: 'swap',
    weight: '100 900',
    variable: '--font-pretendard',
});

/* TODO :: ThemeRegistry로 변경
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
*/

export default function RootLayout({ children }) {
    const pathname = usePathname();
    const path = pathname.split('/');
    const page = path.at(-1);
    const isHome = page == '';
    const isLogin = pathname.includes('login');

    return (
        <html
            lang="ko"
            className={`${pretendard.variable} h-full scroll-smooth text-text-pri font-medium min-h-full`}
        >
            <body className={`${pretendard.className} antialiased h-full`}>
                <div id="wrap" className="flex h-full">
                    <SidebarProvider>
                        <AppSidebar />
                        <main className="grow basis-0 flex flex-col" id="container">
                            <header
                                className="h-[60px] fixed top-0 text-point flex justify-between items-center px-4 bg-zinc-200"
                                style={{
                                    width: 'calc(100% - 255px)',
                                }}
                            >
                                <div className="flex items-center gap-1">
                                    <SidebarTrigger />
                                    <span>사이드바 접기</span>
                                </div>
                                <div className="flex gap-2 items-center">
                                    <a href="#">로그인</a>
                                    <a href="#">회원가입</a>
                                </div>
                            </header>
                            <div className="mt-[60px] p-8" id="contents-wrap">
                                {!isHome && !isLogin && <BreadCrumbs />}
                                {children}
                            </div>
                            <footer className="bg-blue-950 text-white flex flex-col justify-center px-4 h-[40px] w-full mt-auto">
                                <div>Copyright 2025@ deserved</div>
                            </footer>
                        </main>
                    </SidebarProvider>
                </div>
            </body>
        </html>
    );
}
